apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-country-travel-info
  namespace: covid
spec:
  selector:
    matchLabels:
      run: query-country-travel-info
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        run: query-country-travel-info
    spec:
      containers:
      - name: query-country-travel-info
        image: xgis/action-query-country-travel-info
        ports:
        - containerPort: 80
